"""create videos and frame_embeddings tables

Revision ID: a8c3b9f1f1be
Revises: 7f7a494e7e60
Create Date: 2026-03-14 16:04:32.846974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c3b9f1f1be'
down_revision: Union[str, Sequence[str], None] = '7f7a494e7e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('frame_embeddings', 'video_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_frame_embeddings_video_id'), 'frame_embeddings', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_frame_embeddings_video_id'), table_name='frame_embeddings')
    op.alter_column('frame_embeddings', 'video_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
